#!/bin/ksh

#set -x

# Software versions, uncomment installed software
APACHE13_VERSION=1.3.28
APACHE13_MODPYTHON_VERSION=2.7.8
DMERCE_VERSION=2.5.0
JAVA_VERSION=1.4.1_01
JAVA_JMAGICK_VERSION=5.5.6-0
IMAGEMAGICK_VERSION=5.5.7
MYSQL_VERSION=3.23.57
ORACLE_VERSION=8.1.7
PGSQL_VERSION=7.3.4
PHP_VERSION=4.3.1
PYTHON1_VERSION=1.5.2
PYTHON2_VERSION=2.2.2
PYTHON2_EGENIX_MXDATETIME_VERSION=2.0.3
PYTHON2_MYSQL_VERSION=0.9.2
PYTHON2_PSYCOPG_VERSION=1.0.13
COURIER_IMAP_VERSION=1.7.1
EXIM_VERSION=4.14

# Start/stop
DMERCE_ST=YES
APACHE1312_ST=NO
APACHE13_ST=YES
DMERCE_ST=YES
MYSQL_ST=YES
PGSQL_ST=NO
ORACLE_ST=NO
COURIER_IMAP_ST=NO
EXIM_ST=NO

#
# Functions
#

look_for_prg() {
    #set -x

    VAR=$1
    shift
    PRG=$1
    shift
    while [ $# -gt 0 ]; do
	if [ -d $1 ]; then
	    if [ -f $1/$PRG ]; then
		e="$VAR=$1/$PRG"
		eval $e
		break
	    fi
	fi
	shift
    done
    export $VAR
}

setvar_if_fd_exists() {
    #set -x

    VAR=$1
    shift
    P=$1
    if [ -z "$INSTALL_MODE" ]; then
	INSTALL_MODE=0
    fi
    if [ $INSTALL_MODE -eq 1 ]; then
	e="$VAR=$P"
    else
	[ -d $P -o -f $P ] && e="$VAR=$P"
    fi
    eval $e
    export $VAR
}

add_to_ld_library_path() {
    #set -x

    if [ -d $1 ]; then
	if [ -n "$LD_LIBRARY_PATH" ]; then
	    case "$LD_LIBRARY_PATH" in
		*$1*)
		    ;;
		*)
		    LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
		    ;;
	    esac
	else
	    LD_LIBRARY_PATH=$1
	fi
    fi
}

add_to_path() {
    #set -x

    if [ -d $1 ]; then
	if [ -n "$PATH" ]; then
	    case "$PATH" in
		*$1*)
		    ;;
		*)
		    PATH=$1:$PATH
		    ;;
	    esac
	else
	    PATH=$1
	fi
    fi
}

add_to_java_classpath() {
    #set -x

    if [ -f $1 -o -d $1 ]; then
	if [ -n "$CLASSPATH" ]; then
	    case "$CLASSPATH" in
		*$1*)
		    ;;
		*)
		    CLASSPATH=$1:$CLASSPATH
		    ;;
	    esac
	else
	    CLASSPATH=$1
	fi
    fi
}

# dmerce
DMERCE_HOME=/opt/dmerce
DMERCE_BIN=$DMERCE_HOME/bin
DMERCE_BUILD=$DMERCE_HOME/build
DMERCE_DOC=$DMERCE_HOME/doc
DMERCE_EXAMPLES=$DMERCE_HOME/examples
DMERCE_INSTALL=$DMERCE_HOME/install
DMERCE_LANG=german
DMERCE_LIB=$DMERCE_HOME/lib
DMERCE_LOG=$DMERCE_HOME/log
DMERCE_PRODUCT=$DMERCE_HOME/product
DMERCE_JAR=$DMERCE_PRODUCT/jar
DMERCE_SCRATCH=$DMERCE_HOME/scratch
DMERCE_SQL=$DMERCE_HOME/sql
DMERCE_SQL_MYSQL=$DMERCE_HOME/sql/mysql/dmerce
DMERCE_SQL_ORACLE=$DMERCE_HOME/sql/oracle/dmerce
DMERCE_SQL_POSTGRESQL=$DMERCE_HOME/sql/postgresql/dmerce
DMERCE_WEBSITES=$DMERCE_HOME/websites

# Python
setvar_if_fd_exists PYTHON1_HOME $DMERCE_PRODUCT/python/$PYTHON1_VERSION
setvar_if_fd_exists PYTHON2_HOME $DMERCE_PRODUCT/python/$PYTHON2_VERSION
setvar_if_fd_exists PYTHON2_NT_HOME $DMERCE_PRODUCT/python/$PYTHON2_VERSION-nt

# Apache
setvar_if_fd_exists APACHE13_HOME $DMERCE_PRODUCT/apache/$APACHE13_VERSION
setvar_if_fd_exists APACHE1312_HOME $DMERCE_PRODUCT/apache/1.3.12
setvar_if_fd_exists APACHE13_MODPYTHON_VERSION 2.7.8
setvar_if_fd_exists PHP_HOME $DMERCE_PRODUCT/php/$PHP_VERSION
setvar_if_fd_exists PHPRC $PHP_HOME/lib/php

# MySQL
setvar_if_fd_exists MYSQL_HOME $DMERCE_PRODUCT/mysql/$MYSQL_VERSION
setvar_if_fd_exists MYSQL_JDBC mysql-connector-java-2.0.14-bin.jar
MYSQL_ROOTPWD=
MYSQL_USER=dmerce

# PostgreSQL
setvar_if_fd_exists PGSQL_HOME $DMERCE_PRODUCT/postgresql/$PGSQL_VERSION
setvar_if_fd_exists PGDATA $PGSQL_HOME/data
setvar_if_fd_exists PGSQL_JDBC pg73jdbc3.jar
PGSQL_USER=dmerce

# ORACLE
setvar_if_fd_exists ORACLE_BASE $DMERCE_PRODUCT/oracle
setvar_if_fd_exists ORACLE_HOME $ORACLE_BASE/product/$ORACLE_VERSION
setvar_if_fd_exists ORACLE_LIB $ORACLE_HOME/lib
ORACLE_SID=dmerce
NLS_LANG=american_america.WE8ISO8859P15

# Java
setvar_if_fd_exists JAVA_HOME $DMERCE_PRODUCT/j2sdk$JAVA_VERSION

# Courier
setvar_if_fd_exists COURIER_IMAP_HOME $DMERCE_PRODUCT/courier/$COURIER_IMAP_VERSION

# Exim
setvar_if_fd_exists EXIM_HOME $DMERCE_PRODUCT/exim/$EXIM_VERSION
EXIM_QUEUE_TIME="30m"

# Path
PATH=$PATH
add_to_path /usr/local/bin
add_to_path $DMERCE_BIN
add_to_path $MYSQL_HOME/bin
add_to_path $PGSQL_HOME/bin
add_to_path $ORACLE_HOME/bin
add_to_path $JAVA_HOME/bin

# Library path
LD_LIBRARY_PATH=$LD_LIBRARY_PATH
add_to_ld_library_path /usr/lib
add_to_ld_library_path /usr/local/lib
add_to_ld_library_path /opt/sfw/lib
add_to_ld_library_path $MYSQL_HOME/lib/mysql
add_to_ld_library_path $PGSQL_HOME/lib
add_to_ld_library_path $ORACLE_LIB
add_to_ld_library_path $DMERCE_PRODUCT/JMagick/$JAVA_JMAGICK_VERSION/lib
add_to_ld_library_path $DMERCE_PRODUCT/ImageMagick/$IMAGEMAGICK_VERSION/lib

# Java classpath
CLASSPATH=$CLASSPATH
add_to_java_classpath $DMERCE_JAR/dmerce-$DMERCE_VERSION.jar
add_to_java_classpath $DMERCE_JAR/jdom.jar
add_to_java_classpath $DMERCE_JAR/$MYSQL_JDBC
add_to_java_classpath $DMERCE_JAR/$PGSQL_JDBC
add_to_java_classpath $DMERCE_PRODUCT/JMagick/$JAVA_JMAGICK_VERSION/lib/jmagick.jar

# Locale
qd_set_locale() {
    LC_MESSAGES=C
    LC_TIME=en_US.ISO8859-1
    LC_NUMERIC=en_US.ISO8859-1
    LC_CTYPE=en_US.ISO8859-1
    LC_MONETARY=en_US.ISO8859-1
    LC_COLLATE=en_US.ISO8859-1
    export LC_MESSAGES
    export LC_TIME
    export LC_NUMERIC
    export LC_CTYPE
    export LC_MONETARY
    export LC_COLLATE
}

check_ssh() {
    [ ! -d .ssh ] && mkdir .ssh
    chmod 700 .ssh
}

info() {
    echo "* To change this type:"
    echo "* qd_set24_env for dmerce 2.4"
    echo "* qd_set25_env for dmerce 2.5"
    echo "*"
    echo
}

# dmerce 2.4
qd_set24_env() {
    echo "*"
    echo "* Setting dmerce 2.4 environment"
    echo "*"
    info
    PYTHONPATH=$DMERCE_PRODUCT/dmerce/2.4.0:$DMERCE_PRODUCT/dmerce/2.4.0/DTL:$DMERCE_PRODUCT/dmerce/2.4.0/DMS
    PATH=$PYTHON1_HOME/bin:$PATH
    qd_export_env
}

# dmerce 2.5
qd_set25_env() {
    echo "*"
    echo "* Setting dmerce 2.5 environment"
    echo "*"
    info
    PYTHONPATH=$DMERCE_PRODUCT/dmerce/2.5.0:$DMERCE_PRODUCT/dmerce/2.5.0/DTL:$DMERCE_PRODUCT/dmerce/2.5.0/DMS
    PATH=$PYTHON2_NT_HOME/bin:$PATH
    qd_export_env
}

# Export environment
qd_export_env() {
    # dmerce
    export DMERCE_VERSION
    export IMAGEMAGICK_VERSION
    export ORACLE_VERSION
    export COURIER_IMAP_VERSION
    export EXIM_VERSION
    export DMERCE_HOME
    export DMERCE_BIN
    export DMERCE_BUILD
    export DMERCE_DOC
    export DMERCE_EXAMPLES
    export DMERCE_INSTALL
    export DMERCE_JAR
    export DMERCE_LANG
    export DMERCE_LIB
    export DMERCE_LOG
    export DMERCE_PRODUCT
    export DMERCE_SCRATCH
    export DMERCE_SQL
    export DMERCE_SQL_MYSQL
    export DMERCE_SQL_ORACLE
    export DMERCE_SQL_POSTGRESQL
    export DMERCE_WEBSITES

    # Python
    export PYTHON1_VERSION
    export PYTHON2_VERSION
    export PYTHON2_HOME
    export PYTHON2_NT_HOME
    export PYTHONPATH
    export PYTHON2_EGENIX_MXDATETIME_VERSION
    export PYTHON2_MYSQL_VERSION
    export PYTHON2_PSYCOPG_VERSION

    # Java
    export JAVA_HOME
    export CLASSPATH
    export JAVA_VERSION
    export JAVA_JMAGICK_VERSION

    # Apache
    export APACHE13_VERSION
    export APACHE13_HOME
    export APACHE13_MODPYTHON_VERSION
    export PHP_HOME
    export PHPRC
    export PHP_VERSION

    # MySQL
    export MYSQL_VERSION
    export MYSQL_HOME
    export MYSQL_ROOTPWD
    export MYSQL_USER

    # PostgreSQL
    export PGSQL_VERSION
    export PGSQL_HOME
    export PGDATA

    # ORACLE
    export ORACLE_BASE
    export ORACLE_HOME
    export ORACLE_LIB
    export ORACLE_SID
    export NLS_LANG

    # Paths
    export LD_LIBRARY_PATH
    export PATH

    # Set umask
    umask 007

    # Check SSH directory
    check_ssh
}
