CONNECT SYS/$DMERCE_ORACLE_SYSDBAPWD AS SYSDBA
SET ECHO OFF
SPOOL $DMERCE_HOME/log/crdb$DMERCE_ORACLE_VER/$DMERCE_ORACLE_INST/crdbfiles.log
CREATE TABLESPACE "DRSYS" LOGGING DATAFILE '$DMERCE_ORACLE_DATAFILES/$DMERCE_ORACLE_INST/drsys01.dbf' SIZE 20480K REUSE AUTOEXTEND ON NEXT  640K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE "INDX" LOGGING DATAFILE '$DMERCE_ORACLE_DATAFILES/$DMERCE_ORACLE_INST/indx01.dbf' SIZE 25M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
CREATE TEMPORARY TABLESPACE "TEMP" TEMPFILE '$DMERCE_ORACLE_DATAFILES/$DMERCE_ORACLE_INST/temp01.dbf' SIZE 25M REUSE AUTOEXTEND ON NEXT  640K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE "TEMP";
CREATE TABLESPACE "TOOLS" LOGGING DATAFILE '$DMERCE_ORACLE_DATAFILES/$DMERCE_ORACLE_INST/tools01.dbf' SIZE 10M REUSE AUTOEXTEND ON NEXT  320K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE "USERS" LOGGING DATAFILE '$DMERCE_ORACLE_DATAFILES/$DMERCE_ORACLE_INST/users01.dbf' SIZE 25M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;
SPOOL OFF
EXIT;
