//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 06:31:07 CET 
//


package com.wanci.dmerce.workflow.xmlbridge;


/**
 * Java content class for CONDITION complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="CONDITION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameter" type="{http://www.1ci.de}PARAMETER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="formfield" type="{http://www.1ci.de}FORMFIELD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="javaclass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CONDITION {


    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getValue();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setValue(java.lang.String value);

    /**
     * Gets the value of the Formfield property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there's any setter method for the Formfield property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormfield().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.wanci.dmerce.workflow.xmlbridge.FORMFIELD}
     * 
     */
    java.util.List getFormfield();

    /**
     * Gets the value of the Parameter property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there's any setter method for the Parameter property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.wanci.dmerce.workflow.xmlbridge.PARAMETER}
     * 
     */
    java.util.List getParameter();

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getJavaclass();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setJavaclass(java.lang.String value);

}
