//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 06:31:07 CET 
//


package com.wanci.dmerce.workflow.xmlbridge;


/**
 * Java content class for FORMMAP complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="FORMMAP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fieldmap" type="{http://www.1ci.de}FIELDMAP" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="table" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primarykey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FORMMAP {


    /**
     * Gets the value of the Fieldmap property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there's any setter method for the Fieldmap property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldmap().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.wanci.dmerce.workflow.xmlbridge.FIELDMAP}
     * 
     */
    java.util.List getFieldmap();

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getPrimarykey();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setPrimarykey(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getTable();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setTable(java.lang.String value);

}
