//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 06:31:07 CET 
//


package com.wanci.dmerce.workflow.xmlbridge;


/**
 * Java content class for TRANSITION complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="TRANSITION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.1ci.de}CONDITION" minOccurs="0"/>
 *         &lt;element name="action" type="{http://www.1ci.de}ACTION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface TRANSITION {


    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.workflow.xmlbridge.ACTION}
     */
    com.wanci.dmerce.workflow.xmlbridge.ACTION getAction();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.workflow.xmlbridge.ACTION}
     */
    void setAction(com.wanci.dmerce.workflow.xmlbridge.ACTION value);

    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.workflow.xmlbridge.CONDITION}
     */
    com.wanci.dmerce.workflow.xmlbridge.CONDITION getCondition();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.workflow.xmlbridge.CONDITION}
     */
    void setCondition(com.wanci.dmerce.workflow.xmlbridge.CONDITION value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getUrl();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setUrl(java.lang.String value);

    boolean isValidation();

    void setValidation(boolean value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setName(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getTarget();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setTarget(java.lang.String value);

}
