CONNECT SYS/$DMERCE_ORACLE_SYSDBAPWD as SYSDBA
SET ECHO OFF
SPOOL $DMERCE_HOME/logs/orclcrrbs$oracle_ver.log
CREATE ROLLBACK SEGMENT rb_temp STORAGE (INITIAL 100 k NEXT 250 k);
ALTER ROLLBACK SEGMENT rb_temp ONLINE;
CREATE TABLESPACE rbs
       DATAFILE '$DMERCE_ORACLE_DATAFILES/rbs01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE 150M;
CREATE TABLESPACE users
       DATAFILE '$DMERCE_ORACLE_DATAFILES/users01.dbf' SIZE 3M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE 150M;
CREATE TABLESPACE temp
       DATAFILE '$DMERCE_ORACLE_DATAFILES/temp01.dbf' SIZE 2M REUSE AUTOEXTEND ON NEXT 5M MAXSIZE 150M;
CREATE ROLLBACK SEGMENT rb1 STORAGE(INITIAL 50K NEXT 250K)
       TABLESPACE rbs;
CREATE ROLLBACK SEGMENT rb2 STORAGE(INITIAL 50K NEXT 250K)
       TABLESPACE rbs;
CREATE ROLLBACK SEGMENT rb3 STORAGE(INITIAL 50K NEXT 250K)
       TABLESPACE rbs;
CREATE ROLLBACK SEGMENT rb4 STORAGE(INITIAL 50K NEXT 250K)
       TABLESPACE rbs;
ALTER ROLLBACK SEGMENT rb1 ONLINE;
ALTER ROLLBACK SEGMENT rb2 ONLINE;
ALTER ROLLBACK SEGMENT rb3 ONLINE;
ALTER ROLLBACK SEGMENT rb4 ONLINE;
ALTER ROLLBACK SEGMENT rb_temp OFFLINE;
DROP ROLLBACK SEGMENT rb_temp;
SPOOL OFF
EXIT;
