//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.09 at 04:45:04 CET 
//


package com.wanci.dmerce.forms;


/**
 * Java content class for FIELD complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="FIELD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displaytype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="displayformat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="options" type="{http://www.1ci.de}OPTIONS" minOccurs="0"/>
 *         &lt;element name="constraints" type="{http://www.1ci.de}CONSTRAINTS" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://www.1ci.de}MESSAGES" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface FIELD {


    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getDisplaytype();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setDisplaytype(java.lang.String value);

    boolean isRequired();

    void setRequired(boolean value);

    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.forms.CONSTRAINTS}
     */
    com.wanci.dmerce.forms.CONSTRAINTS getConstraints();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.forms.CONSTRAINTS}
     */
    void setConstraints(com.wanci.dmerce.forms.CONSTRAINTS value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getDescription();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setDescription(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.forms.OPTIONS}
     */
    com.wanci.dmerce.forms.OPTIONS getOptions();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.forms.OPTIONS}
     */
    void setOptions(com.wanci.dmerce.forms.OPTIONS value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getDisplayformat();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setDisplayformat(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setName(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.forms.MESSAGES}
     */
    com.wanci.dmerce.forms.MESSAGES getMessages();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.forms.MESSAGES}
     */
    void setMessages(com.wanci.dmerce.forms.MESSAGES value);

}
