//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.03.09 at 04:45:04 CET 
//


package com.wanci.dmerce.forms;


/**
 * Java content class for PERIOD complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="PERIOD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="enddate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface PERIOD {


    /**
     * 
     * @return possible object is
     * {@link java.util.Calendar}
     */
    java.util.Calendar getStartdate();

    /**
     * 
     * @param value allowed object is
     * {@link java.util.Calendar}
     */
    void setStartdate(java.util.Calendar value);

    /**
     * 
     * @return possible object is
     * {@link java.util.Calendar}
     */
    java.util.Calendar getEnddate();

    /**
     * 
     * @param value allowed object is
     * {@link java.util.Calendar}
     */
    void setEnddate(java.util.Calendar value);

}
