//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 06:31:07 CET 
//


package com.wanci.dmerce.workflow.xmlbridge.impl;

public class TRANSITIONImpl implements com.wanci.dmerce.workflow.xmlbridge.TRANSITION, com.sun.xml.bind.JAXBObject, com.wanci.dmerce.workflow.xmlbridge.impl.runtime.UnmarshallableObject, com.wanci.dmerce.workflow.xmlbridge.impl.runtime.XMLSerializable, com.wanci.dmerce.workflow.xmlbridge.impl.runtime.ValidatableObject
{

    protected com.wanci.dmerce.workflow.xmlbridge.ACTION _Action;
    protected com.wanci.dmerce.workflow.xmlbridge.CONDITION _Condition;
    protected java.lang.String _Url;
    protected boolean has_Validation;
    protected boolean _Validation;
    protected java.lang.String _Name;
    protected java.lang.String _Target;
    public final static java.lang.Class version = (com.wanci.dmerce.workflow.xmlbridge.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.wanci.dmerce.workflow.xmlbridge.TRANSITION.class);
    }

    public com.wanci.dmerce.workflow.xmlbridge.ACTION getAction() {
        return _Action;
    }

    public void setAction(com.wanci.dmerce.workflow.xmlbridge.ACTION value) {
        _Action = value;
    }

    public com.wanci.dmerce.workflow.xmlbridge.CONDITION getCondition() {
        return _Condition;
    }

    public void setCondition(com.wanci.dmerce.workflow.xmlbridge.CONDITION value) {
        _Condition = value;
    }

    public java.lang.String getUrl() {
        return _Url;
    }

    public void setUrl(java.lang.String value) {
        _Url = value;
    }

    public boolean isValidation() {
        if (!has_Validation) {
            return javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.DatatypeConverterImpl.installHook("true"));
        } else {
            return _Validation;
        }
    }

    public void setValidation(boolean value) {
        _Validation = value;
        has_Validation = true;
    }

    public java.lang.String getName() {
        return _Name;
    }

    public void setName(java.lang.String value) {
        _Name = value;
    }

    public java.lang.String getTarget() {
        return _Target;
    }

    public void setTarget(java.lang.String value) {
        _Target = value;
    }

    public com.wanci.dmerce.workflow.xmlbridge.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.UnmarshallingContext context) {
        return new com.wanci.dmerce.workflow.xmlbridge.impl.TRANSITIONImpl.Unmarshaller(context);
    }

    public void serializeElementBody(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Condition!= null) {
            context.startElement("http://www.1ci.de", "condition");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endElement();
        }
        if (_Action!= null) {
            context.startElement("http://www.1ci.de", "action");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Action));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Action));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Action));
            context.endElement();
        }
    }

    public void serializeAttributes(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Target!= null) {
            context.startAttribute("", "target");
            try {
                context.text(((java.lang.String) _Target));
            } catch (java.lang.Exception e) {
                com.wanci.dmerce.workflow.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (has_Validation) {
            context.startAttribute("", "validation");
            try {
                context.text(javax.xml.bind.DatatypeConverter.printBoolean(((boolean) _Validation)));
            } catch (java.lang.Exception e) {
                com.wanci.dmerce.workflow.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_Url!= null) {
            context.startAttribute("", "url");
            try {
                context.text(((java.lang.String) _Url));
            } catch (java.lang.Exception e) {
                com.wanci.dmerce.workflow.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        context.startAttribute("", "name");
        try {
            context.text(((java.lang.String) _Name));
        } catch (java.lang.Exception e) {
            com.wanci.dmerce.workflow.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
    }

    public void serializeAttributeBody(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Condition!= null) {
            context.startElement("http://www.1ci.de", "condition");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Condition));
            context.endElement();
        }
        if (_Action!= null) {
            context.startElement("http://www.1ci.de", "action");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Action));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Action));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Action));
            context.endElement();
        }
    }

    public void serializeURIs(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.wanci.dmerce.workflow.xmlbridge.TRANSITION.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\n\u00e4\u00c3\"ppsq\u0000~\u0000\u0000\bN>\u00e8ppsq\u0000~\u0000\u0000\u0005"
+"\u0093\u00be\u00abppsq\u0000~\u0000\u0000\u0002JR\u0012ppsq\u0000~\u0000\u0000\u0000-!\u00cbppsr\u0000\u001dcom.sun.msv.grammar.ChoiceE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0000\u0016\u0090\u00e3ppsr\u0000\'com.sun.msv.grammar.trex.Elemen"
+"tPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameC"
+"lass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreU"
+"ndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u0016\u0090\u00d8sr\u0000\u0011java.la"
+"ng.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\f\u0000\u0016\u0090\u00cdpp\u0000sq\u0000~\u0000\n\u0000\u0016\u0090\u00c2pps"
+"r\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.ms"
+"v.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u0016\u0090\u00b7q\u0000~\u0000\u0011psr\u0000 "
+"com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnam"
+"eClassq\u0000~\u0000\rxq\u0000~\u0000\u0003\u0000\u0016\u0090\u00b4q\u0000~\u0000\u0011psr\u00002com.sun.msv.grammar.Expressio"
+"n$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u0010\u0001psr\u0000 com.su"
+"n.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar"
+".NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$Ep"
+"silonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u001bpsr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/St"
+"ring;L\u0000\fnamespaceURIq\u0000~\u0000\"xq\u0000~\u0000\u001dt\u0000-com.wanci.dmerce.workflow."
+"xmlbridge.CONDITIONt\u0000+http://java.sun.com/jaxb/xjc/dummy-ele"
+"mentssq\u0000~\u0000!t\u0000\tconditiont\u0000\u0011http://www.1ci.deq\u0000~\u0000 sq\u0000~\u0000\n\u0000\u0016\u0090\u00e3pp"
+"sq\u0000~\u0000\f\u0000\u0016\u0090\u00d8q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\f\u0000\u0016\u0090\u00cdpp\u0000sq\u0000~\u0000\n\u0000\u0016\u0090\u00c2ppsq\u0000~\u0000\u0014\u0000\u0016\u0090\u00b7q\u0000~\u0000\u0011psq"
+"\u0000~\u0000\u0017\u0000\u0016\u0090\u00b4q\u0000~\u0000\u0011pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000*com.wanci.dmerce.workf"
+"low.xmlbridge.ACTIONq\u0000~\u0000%sq\u0000~\u0000!t\u0000\u0006actionq\u0000~\u0000(q\u0000~\u0000 sq\u0000~\u0000\n\u0002\u001d0B"
+"ppsq\u0000~\u0000\u0017\u0002\u001d07q\u0000~\u0000\u0011psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003"
+"L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004name"
+"t\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0000\u00ff$#ppsr\u0000#com.sun.msv."
+"datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.su"
+"n.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.m"
+"sv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datat"
+"ype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\"L\u0000\btype"
+"Nameq\u0000~\u0000\"L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpac"
+"eProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u0000"
+"5com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d"
+"\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\"L\u0000\fnamespaceURIq\u0000~\u0000\"xpq\u0000~\u0000@q\u0000~\u0000?sq\u0000~\u0000!t"
+"\u0000\u0006targett\u0000\u0000q\u0000~\u0000 sq\u0000~\u0000\n\u0003Il\u0094ppsq\u0000~\u0000\u0017\u0003Il\u0089q\u0000~\u0000\u0011psq\u0000~\u00005\u0001\u009e\u00839ppsr\u0000$"
+"com.sun.msv.datatype.xsd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000:q\u0000~\u0000?t\u0000"
+"\u0007booleansr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Col"
+"lapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Bq\u0000~\u0000Esq\u0000~\u0000Fq\u0000~\u0000Pq\u0000~\u0000?sq\u0000~\u0000!t\u0000\nvalidati"
+"onq\u0000~\u0000Jq\u0000~\u0000 sq\u0000~\u0000\n\u0002\u00ba\u00808ppsq\u0000~\u0000\u0017\u0002\u00ba\u0080-q\u0000~\u0000\u0011pq\u0000~\u00008sq\u0000~\u0000!t\u0000\u0003urlq\u0000~"
+"\u0000Jq\u0000~\u0000 sq\u0000~\u0000\u0017\u0002\u0096\u00845ppq\u0000~\u00008sq\u0000~\u0000!t\u0000\u0004nameq\u0000~\u0000Jsr\u0000\"com.sun.msv.gr"
+"ammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gr"
+"ammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Ex"
+"pressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006par"
+"entq\u0000~\u0000^[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u000e\u0000\u0000"
+"\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppp"
+"ppppppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u0005ppppppp"
+"pppq\u0000~\u0000\u0006ppppppppppppq\u0000~\u0000\u0007ppppppppppppppppppppppppppppppppq\u0000~"
+"\u0000\bppppppppq\u0000~\u0000\u0016q\u0000~\u0000-pppppppppq\u0000~\u0000\u0013q\u0000~\u0000,ppppppq\u0000~\u0000\tpppppppppp"
+"ppppppq\u0000~\u0000Kppppq\u0000~\u00003ppq\u0000~\u0000\u000bq\u0000~\u0000)ppppppppppq\u0000~\u0000Vppppppppppppp"
+"pppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.wanci.dmerce.workflow.xmlbridge.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------");
        }

        protected Unmarshaller(com.wanci.dmerce.workflow.xmlbridge.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.wanci.dmerce.workflow.xmlbridge.impl.TRANSITIONImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        if (("condition" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  16 :
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("parameter" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("formfield" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  15 :
                        if (("action" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "validation");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText0(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  18 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  13 :
                        attIdx = context.getAttribute("", "value");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("parameter" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("formfield" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterElement((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "target");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "url");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  9 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText0(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Validation = javax.xml.bind.DatatypeConverter.parseBoolean(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_Validation = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Target = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Url = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Name = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  16 :
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromLeaveElement((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "validation");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText0(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  18 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  13 :
                        attIdx = context.getAttribute("", "value");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromLeaveElement((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "target");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "url");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  9 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                    case  17 :
                        if (("action" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("condition" == ___local)&&("http://www.1ci.de" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  16 :
                        if (("type" == ___local)&&("" == ___uri)) {
                            _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("javaclass" == ___local)&&("" == ___uri)) {
                            _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname));
                            return ;
                        }
                        _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  3 :
                        if (("validation" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  18 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  13 :
                        if (("value" == ___local)&&("" == ___uri)) {
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("javaclass" == ___local)&&("" == ___uri)) {
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                            return ;
                        }
                        if (("type" == ___local)&&("" == ___uri)) {
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                            return ;
                        }
                        _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        if (("target" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        if (("url" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  9 :
                        if (("name" == ___local)&&("" == ___uri)) {
                            state = 10;
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        state = 15;
                        continue outer;
                    case  16 :
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromLeaveAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  11 :
                        if (("name" == ___local)&&("" == ___uri)) {
                            state = 12;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("validation" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("target" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        attIdx = context.getAttribute("", "validation");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText0(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  18 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  13 :
                        attIdx = context.getAttribute("", "value");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "javaclass");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "type");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromLeaveAttribute((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "target");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        attIdx = context.getAttribute("", "url");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 9;
                            continue outer;
                        }
                        state = 9;
                        continue outer;
                    case  9 :
                        attIdx = context.getAttribute("", "name");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText3(v);
                            state = 12;
                            continue outer;
                        }
                        break;
                    case  8 :
                        if (("url" == ___local)&&("" == ___uri)) {
                            state = 9;
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  12 :
                            state = 15;
                            continue outer;
                        case  16 :
                            attIdx = context.getAttribute("", "type");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "javaclass");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _Action = ((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl) spawnChildFromText((com.wanci.dmerce.workflow.xmlbridge.impl.ACTIONImpl.class), 17, value));
                            return ;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  3 :
                            attIdx = context.getAttribute("", "validation");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText0(v);
                                state = 6;
                                continue outer;
                            }
                            state = 6;
                            continue outer;
                        case  18 :
                            revertToParentFromText(value);
                            return ;
                        case  4 :
                            eatText0(value);
                            state = 5;
                            return ;
                        case  13 :
                            attIdx = context.getAttribute("", "value");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "javaclass");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "type");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _Condition = ((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl) spawnChildFromText((com.wanci.dmerce.workflow.xmlbridge.impl.CONDITIONImpl.class), 14, value));
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "target");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  6 :
                            attIdx = context.getAttribute("", "url");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText2(v);
                                state = 9;
                                continue outer;
                            }
                            state = 9;
                            continue outer;
                        case  9 :
                            attIdx = context.getAttribute("", "name");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText3(v);
                                state = 12;
                                continue outer;
                            }
                            break;
                        case  7 :
                            eatText2(value);
                            state = 8;
                            return ;
                        case  10 :
                            eatText3(value);
                            state = 11;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
