-- #############################################################################################
--
-- %Purpose: Show Tablespace Status Information
--
-- #############################################################################################
--
ttitle  left 'Output generated by: ' sql.user ' at: ' format a8 datum -
skip -
skip -
left  'Tablespace Status' -
skip -
left  'Oracle Version ' format a15 sql.release -
skip 2
set feed off
set pagesize 10000
  column datum new_value datum noprint
column tablespace_name format A64 heading 'Tablespace'
column status format a15 heading "Status"

select  to_char(sysdate, 'MM/DD/YY') datum,
    tablespace_name,
  status
from sys.dba_tablespaces;
