//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.09.05 at 03:14:44 CEST 
//


package com.wanci.dmerce.webservice.db.xmlbridge;


/**
 * Java content class for anonymous complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="meta" type="{http://www.wanci.com}META"/>
 *         &lt;element name="data" type="{http://www.wanci.com}DATA"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RdbsdataType {


    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.webservice.db.xmlbridge.DATA}
     */
    com.wanci.dmerce.webservice.db.xmlbridge.DATA getData();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.webservice.db.xmlbridge.DATA}
     */
    void setData(com.wanci.dmerce.webservice.db.xmlbridge.DATA value);

    /**
     * 
     * @return possible object is
     * {@link com.wanci.dmerce.webservice.db.xmlbridge.META}
     */
    com.wanci.dmerce.webservice.db.xmlbridge.META getMeta();

    /**
     * 
     * @param value allowed object is
     * {@link com.wanci.dmerce.webservice.db.xmlbridge.META}
     */
    void setMeta(com.wanci.dmerce.webservice.db.xmlbridge.META value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getError();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setError(java.lang.String value);

}
