create table t_accounts (
	id					number not null,
	c1 number,
	c2 float,
	c3 number,
	c4 float,
	username			varchar2(100) not null,
	password			varchar2(16) not null,
	customerid			number not null,
	existsatmediaways	number(1),
	lastmediawaysmsg	varchar2(100),
	mediawaysmsgdate	date,
	inprogress			number(1)
);

create table t_mig_customer (
	id					number not null,
	c1 number,
	c2 float,
	c3 number,
	c4 float,
	a1 number(1),
	gender				number,
	firstname			varchar2(100) not null,
	lastname			varchar2(100) not null,
	street				varchar2(100) not null,
	zipcode				char(5) not null,
	city				varchar2(100) not null,
	phone				varchar2(100) not null,
	email				varchar2(100) not null,
	birthday			date,
	accountnumber		number(10) not null,
	accountowner		varchar2(100) not null,
	bankcode			number(8) not null,
	bank				varchar2(100) not null,
	tacread				number(1) not null,
	rowread				number(1) not null,
	startdate float,
	startdatedate date,
	accountstart float,
	accountstartdate date,
	accountend float,
	accountenddate date,
	statusid			number,
	resellerid			number,
	productid			number,
	remarks 			varchar2(1000),
	deleted				number(1),
	manuellchecked		number(1),
	welcomeemailsent	number(1),
	inprogress			number(1)
);

create table t_customer (
	id					number not null,
	gender				number,
	firstname			varchar2(100) not null,
	lastname			varchar2(100) not null,
	street				varchar2(100) not null,
	zipcode				char(5) not null,
	city				varchar2(100) not null,
	phone				varchar2(100) not null,
	email				varchar2(100) not null,
	birthday			date,
	accountnumber		number(10) not null,
	accountowner		varchar2(100) not null,
	bankcode			number(8) not null,
	bank				varchar2(100) not null,
	tacread				number(1) not null,
	rowread				number(1) not null,
	statusid			number,
	resellerid			number,
	productid			number,
	desiredstartdate	date,
	remarks 			varchar2(1000),
	deleted				number(1),
	manuellchecked		number(1),
	welcomeemailsent	number(1),
	inprogress			number(1)
);

create table t_product (
	id					number not null,
	originalname		varchar2(100) not null,
	runtimemonth		number
);

create table t_reseller (
	id					number not null,
	login				varchar2(100) not null,
	password			varchar2(100) not null,
	logindisabled		number(1) not null default 0,
	company				varchar2(100),
	lastname			varchar2(100) not null,
	firstname			varchar2(100) not null,
	street				varchar2(100),
	zipcode				char(5),
	city				varchar2(100),
	phone				varchar2(100),
	fax					varchar2(100),
	mobilephone			varchar2(100),
	email				varchar2(100),
	url					varchar2(100),
	accountnumber		number(10),
	accountowner		varchar2(100),
	bankcode			number(8),
	bank				varchar2(100),
	resellersince		date,
	remarks				varchar2(1000),
	text1				varchar2(4000),
	text2				varchar2(4000),
	text3				varchar2(4000),
	text4				varchar2(4000),
	text5				varchar2(4000),
	maxfreeaccounts		number,
	acclow				number,
	acchigh				number
);

create table t_resellerproduct (
	id					number not null,
	name				varchar2(100) not null,
	description			varchar2(200),
	price				number,
	installationcost	number,
	resellerid			number not null,
	productid			number not null
);
