//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.09.05 at 03:14:44 CEST 
//


package com.wanci.dmerce.webservice.db.xmlbridge.impl;

public class RdbsdataTypeImpl implements com.wanci.dmerce.webservice.db.xmlbridge.RdbsdataType, com.sun.xml.bind.JAXBObject, com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.UnmarshallableObject, com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.XMLSerializable, com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.ValidatableObject
{

    protected com.wanci.dmerce.webservice.db.xmlbridge.DATA _Data;
    protected com.wanci.dmerce.webservice.db.xmlbridge.META _Meta;
    protected java.lang.String _Error;
    public final static java.lang.Class version = (com.wanci.dmerce.webservice.db.xmlbridge.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.wanci.dmerce.webservice.db.xmlbridge.RdbsdataType.class);
    }

    public com.wanci.dmerce.webservice.db.xmlbridge.DATA getData() {
        return _Data;
    }

    public void setData(com.wanci.dmerce.webservice.db.xmlbridge.DATA value) {
        _Data = value;
    }

    public com.wanci.dmerce.webservice.db.xmlbridge.META getMeta() {
        return _Meta;
    }

    public void setMeta(com.wanci.dmerce.webservice.db.xmlbridge.META value) {
        _Meta = value;
    }

    public java.lang.String getError() {
        return _Error;
    }

    public void setError(java.lang.String value) {
        _Error = value;
    }

    public com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.UnmarshallingContext context) {
        return new com.wanci.dmerce.webservice.db.xmlbridge.impl.RdbsdataTypeImpl.Unmarshaller(context);
    }

    public void serializeElementBody(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://www.wanci.com", "meta");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endAttributes();
        context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endElement();
        context.startElement("http://www.wanci.com", "data");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Data));
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Data));
        context.endAttributes();
        context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Data));
        context.endElement();
        context.startElement("http://www.wanci.com", "error");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Error));
        } catch (java.lang.Exception e) {
            com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeAttributes(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeAttributeBody(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://www.wanci.com", "meta");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endAttributes();
        context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Meta));
        context.endElement();
        context.startElement("http://www.wanci.com", "data");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Data));
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Data));
        context.endAttributes();
        context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _Data));
        context.endElement();
        context.startElement("http://www.wanci.com", "error");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Error));
        } catch (java.lang.Exception e) {
            com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeURIs(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.wanci.dmerce.webservice.db.xmlbridge.RdbsdataType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0002\u00d9\u0080\u008eppsq\u0000~\u0000\u0000\u0002x\u00e7Oppsr\u0000\'com"
+".sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst"
+"\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.Ele"
+"mentExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentMod"
+"elq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001<s\u00a5pp\u0000sq\u0000~\u0000\u0007\u0001<s\u009app\u0000sr\u0000\u001dcom.sun.msv.grammar.Cho"
+"iceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0001<s\u008fppsr\u0000 com.sun.msv.grammar.OneOrMo"
+"reExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L"
+"\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001<s\u0084sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005value"
+"xp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~"
+"\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\bxq\u0000~\u0000\u0003\u0001<s\u0081q\u0000~\u0000\u0012psr\u00002com.sun.msv.grammar.E"
+"xpression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u0011\u0001psr"
+"\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv"
+".grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expre"
+"ssion$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0017psr\u0000#com.su"
+"n.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava"
+"/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001exq\u0000~\u0000\u0019t\u0000-com.wanci.dmerce.w"
+"ebservice.db.xmlbridge.METAt\u0000+http://java.sun.com/jaxb/xjc/d"
+"ummy-elementssq\u0000~\u0000\u001dt\u0000\u0004metat\u0000\u0014http://www.wanci.comsq\u0000~\u0000\u0007\u0001<s\u00a5p"
+"p\u0000sq\u0000~\u0000\u0007\u0001<s\u009app\u0000sq\u0000~\u0000\f\u0001<s\u008fppsq\u0000~\u0000\u000e\u0001<s\u0084q\u0000~\u0000\u0012psq\u0000~\u0000\u0013\u0001<s\u0081q\u0000~\u0000\u0012pq"
+"\u0000~\u0000\u0016q\u0000~\u0000\u001aq\u0000~\u0000\u001csq\u0000~\u0000\u001dt\u0000-com.wanci.dmerce.webservice.db.xmlbri"
+"dge.DATAq\u0000~\u0000!sq\u0000~\u0000\u001dt\u0000\u0004dataq\u0000~\u0000$sq\u0000~\u0000\u0007\u0000`\u0099:pp\u0000sr\u0000\u001bcom.sun.msv."
+"grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Data"
+"type;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq"
+"\u0000~\u0000\u0003\u0000`\u0099/ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001"
+"Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicTy"
+"pe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L"
+"\u0000\fnamespaceUriq\u0000~\u0000\u001eL\u0000\btypeNameq\u0000~\u0000\u001eL\u0000\nwhiteSpacet\u0000.Lcom/sun/"
+"msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/"
+"2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpa"
+"ceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd."
+"WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Exp"
+"ression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun."
+"msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001eL\u0000\fnamespaceU"
+"RIq\u0000~\u0000\u001expq\u0000~\u0000:q\u0000~\u00009sq\u0000~\u0000\u001dt\u0000\u0005errorq\u0000~\u0000$sr\u0000\"com.sun.msv.gramma"
+"r.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gramma"
+"r/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expres"
+"sionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq"
+"\u0000~\u0000E[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0006\u0000\u0000\u00009pu"
+"r\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppppppp"
+"ppppppppppq\u0000~\u0000\u0005pppppppq\u0000~\u0000\u0006ppppppppppppppppppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u0010q\u0000~\u0000(p"
+"ppppppppq\u0000~\u0000\rq\u0000~\u0000\'pppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.UnmarshallingContext context) {
            super(context, "----------");
        }

        protected Unmarshaller(com.wanci.dmerce.webservice.db.xmlbridge.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.wanci.dmerce.webservice.db.xmlbridge.impl.RdbsdataTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        if (("sql-statement" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            _Meta = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.METAImpl) spawnChildFromEnterElement((com.wanci.dmerce.webservice.db.xmlbridge.impl.METAImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        if (("data" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        break;
                    case  4 :
                        if (("row" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromEnterElement((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromEnterElement((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  0 :
                        if (("meta" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("error" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  9 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  8 :
                        if (("error" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("data" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("meta" == ___local)&&("http://www.wanci.com" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  4 :
                        _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromLeaveElement((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromEnterAttribute((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromLeaveAttribute((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, ___uri, ___local, ___qname));
                        return ;
                    case  9 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  7 :
                            eatText0(value);
                            state = 8;
                            return ;
                        case  4 :
                            _Data = ((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl) spawnChildFromText((com.wanci.dmerce.webservice.db.xmlbridge.impl.DATAImpl.class), 5, value));
                            return ;
                        case  9 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText0(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Error = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
